before:
  hooks:
  - ./scripts/completions.sh
builds:
- binary: goji
  main: ./
  goos:
  - darwin
  - linux
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0
  flags:
  - -mod=vendor
  ldflags:
  - -s -w -X cmd.version={{.Version}}

release:
  prerelease: auto

universal_binaries:
- replace: true

archives:
- name_template: >-
    {{- .ProjectName }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm }}v{{ .Arm }}{{ end -}}
  format_overrides:
  - goos: windows
    format: zip
  builds_info:
    group: root
    owner: root
  files:
  - README.md
  - LICENSE
  - completions/*

brews:
- name: goji
  homepage: "https://github.com/muandane/homebrew-gitmoji"
  repository:
    owner: muandane
    name: homebrew-gitmoji
  folder: Formula
  dependencies:
  - name: git
  commit_author:
    name: muandane
    email: zmoualhi@outlook.com
  extra_install: |-
    bash_completion.install "completions/goji.bash" => "goji"
    zsh_completion.install "completions/goji.zsh" => "_goji"
    fish_completion.install "completions/goji.fish"

checksum:
  name_template: 'checksums.txt'
