before:
  hooks:
  - go mod tidy
  - ./scripts/manpages.sh
  - ./scripts/completions.sh


builds:
- binary: goji
  main: ./
  goos:
  - darwin
  - windows
  - linux
  goarch:
  - amd64
  - arm64
  - arm
  goarm:
    - "7"
  ignore:
    - goos: windows
      goarch: arm64
    - goos: windows
      goarm: "7"
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X github.com/muandane/goji/cmd.version={{.Version}}

release:
  prerelease: auto

universal_binaries:
- replace: true

archives:
- name_template: >-
    {{- .ProjectName }}_v{{- .Version }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm }}v{{ .Arm }}{{ end -}}
  format_overrides:
  - goos: windows
    format: zip
  builds_info:
    group: root
    owner: root
  files:
  - README.md
  - LICENSE
  - manpages/*
  - completions/*

brews:
- name: goji
  homepage: "https://github.com/muandane/homebrew-tap"
  repository:
    owner: muandane
    name: homebrew-tap
  folder: Formula
  dependencies:
  - name: git
  commit_author:
    name: muandane
    email: zmoualhi@outlook.com
  extra_install: |-
    bash_completion.install "completions/goji.bash" => "goji"
    zsh_completion.install "completions/goji.zsh" => "_goji"
    fish_completion.install "completions/goji.fish"
    man1.install "manpages/goji.1.gz"
winget:
  - publisher: muandane
    license: "Apache-2.0 license"
    copyright: Muandane
    homepage: "https://github.com/muandane/goji"
    short_description: "Commitizen-like Emoji Commit Tool written in Go"
    repository:
      owner: "muandane"
      name: winget-pkgs
      branch: "{{.ProjectName}}-{{.Version}}"
      # pull_request:
      #   enabled: true
      #   draft: false
      #   check_boxes: true
      #   base:
      #     owner: microsoft
      #     name: winget-pkgs
      #     branch: master

checksum:
  name_template: 'checksums.txt'
