before:
  hooks:
  - ./scripts/completions.sh
builds:
- binary: goji
  main: src/
  goos:
  - darwin
  - linux
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0
  flags:
  - -mod=vendor
  ldflags:
  - -s -w -X cmd.version={{.Version}}

release:
  prerelease: auto

universal_binaries:
- replace: true

brews:
- name: goji
  homepage: "https://github.com/muandane/homebrew-muandane"
  repository:
    owner: muandane
    name: homebrew-muandane
  folder: Formula
  commit_author:
    name: muandane
    email: zmoualhi@outlook.com
  extra_install: |-
    bash_completion.install "completions/goji.bash" => "goji"
    zsh_completion.install "completions/goji.zsh" => "_goji"
    fish_completion.install "completions/goji.fish"

checksum:
  name_template: 'checksums.txt'
