Set Shell zsh
Output public/goji-demo.gif
Set BorderRadius 10
Set Framerate 120
Set Width 1400
Set Theme "Horizon"
Sleep 500ms
Type@120ms "goji"
Enter
Sleep 1.5s
Up
Down@300ms 2
Sleep 300ms
Enter
Sleep 1s
Type@200ms "README.md"
Sleep 1s
Enter
Type@300ms "updated goji docs"
Enter
Sleep 1s
Type@200ms "updated readme file with:"
Ctrl+J
Type@200ms "- windows install methode"
Ctrl+J
Type@200ms "- added goji config file doc table"
Enter
Sleep 1s
Left
Sleep 1s
Enter
Sleep 1s
